FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install uv && \
    pip install --upgrade pip && \
    uv pip install --system -r requirements.txt

COPY . .

EXPOSE 8000


CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
